import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
public class Calculations {

/*
 * The calculations class is responsible for creating, removing, sorting and displaying nodes.
 * When you are expanding a node you will get 8 possible states, if you don't reduce the redundant
 * or potentially the same nodes, you will end with massive amount of nodes that you "can" explore.
 * For example if we are trying to create 4 move: 8^4 = 4096 nodes wold be created. This could be us trying to
 * match the centers and bear in mind we haven't even tried solving it.
 * NOTE: calculations does not use history but instead follows a specific path and constantly checks with if and for conditions.
 */

//This will be used when trying to construct a path and to show how many nodes were discovered.
private ArrayList<Node> foundNodesList = new ArrayList<>();


public void getFoundNodesList(){
    System.out.println("Total number of created nodes: "+foundNodesList.size());
}



//This method is used in Part (3)
public LinkedList<Node> expandingMovesCollection(Node givenNode, int[]givenMovesCollection) {
    //instead of constantly calling list_of_all_found_nodes.size(). This variable stores it saving some memory.
    int foundNodesNumber = foundNodesList.size();
    
    List<Node> finalStepsList = new LinkedList<>();
    int[] sideOne = givenNode.getNodeState(0);
    int[] sideTwo = givenNode.getNodeState(1);
    int[] sideThree = givenNode.getNodeState(2);
    int[] sideFour = givenNode.getNodeState(3);


    //generated by ChatGPT
    int[][] forgotten = new int[4][];
    for (int k = 0; k < 4; k++) {
        forgotten[k] = givenNode.getNodeState(k).clone();
    }
    //generated by ChatGPT

    //loops over all possible moves
    for(int i = 0; i < givenMovesCollection.length; i++){

        //gets the move i and looks for that move in case statement below.
        switch (givenMovesCollection[i]) {


            //Top gains side 2 (<<< rotation)
            case 0:
                for(int j = 0; j<3;j++){
                    /*Example:
                     * Side (0)     Side(1)     Side(2)
                     * 000000       111111      222222
                     * will be:
                     * 111000       222111      000222
                     */
                    forgotten[0][j] = sideTwo[j];
                    forgotten[1][j] = sideThree[j];
                    forgotten[2][j] = sideOne[j];
                }
                finalStepsList.add(new Node("Node"+i+foundNodesNumber,
                                            givenNode.nodeName,
                                            forgotten,
                                            givenNode.nodeCost+1));
            break;


            //Top gains side 3 (>>> rotation)
            case 1:
                for(int j = 0; j<3;j++){
                    forgotten[0][j] = sideThree[j];
                    forgotten[1][j] = sideOne[j];
                    forgotten[2][j] = sideTwo[j];
                }
                finalStepsList.add(new Node("Node"+i+foundNodesNumber,
                                                givenNode.nodeName,
                                                forgotten,
                                                givenNode.nodeCost+1));
            break;


            //Right side gains side 2 (<<< rotation)
            case 2:
                for(int j = 0; j<3;j++){
                    if(j+4 != 6){
                    forgotten[0][j+2] = sideTwo[j+4]; //array length is 0-5, will throw err.
                    forgotten[1][j+4] = sideFour[j];
                }else{
                    forgotten[0][j+2] = sideTwo[0];
                    forgotten[1][0] = sideFour[j];
                    
                }
                forgotten[3][j] = sideOne[j+2];
                }
                finalStepsList.add(new Node("Node"+i+foundNodesNumber,
                                                givenNode.nodeName,
                                                forgotten,
                                                givenNode.nodeCost+1));
            break;


            //Right side gains side 4(>>> rotation)
            case 3:
                for(int j = 0; j<3;j++){
                    forgotten[0][j+2] = sideFour[j];
                    if(j+4 != 6){
                    forgotten[1][j+4] = sideOne[j+2];//same here
                    forgotten[3][j] = sideTwo[j+4];
                }else{
                    forgotten[1][0] = sideOne[j+2];
                    forgotten[3][j] = sideTwo[0];
                }
                }
                finalStepsList.add(new Node("Node"+i+foundNodesNumber,
                                                givenNode.nodeName,
                                                forgotten,
                                                givenNode.nodeCost+1));
            break;


            //Left side gains side 3 (>>> rotation)
            case 4:
                for(int j = 0; j<3;j++){
                    if(j+4 != 6){
                    forgotten[0][j+4] = sideThree[j+2];
                    forgotten[2][j+2] = sideFour[j+4];
                    forgotten[3][j+4] = sideOne[j+4];
                }else{
                    forgotten[0][0] = sideThree[j+2];
                    forgotten[2][j+2] = sideFour[0];
                    forgotten[3][0] = sideOne[0];
                }
                }
                finalStepsList.add(new Node("Node"+i+foundNodesNumber,
                                                givenNode.nodeName,
                                                forgotten,
                                                givenNode.nodeCost+1));
            break;


            //left side gains side 4 (<<< rotation)
            case 5:
                for(int j = 0; j<3;j++){
                    if(j+4 != 6){
                    forgotten[0][j+4] = sideFour[j+4];
                    forgotten[2][j+2] = sideOne[j+4];
                    forgotten[3][j+4] = sideThree[j+2];
                }else{
                    forgotten[0][0] = sideFour[0];
                    forgotten[2][j+2] = sideOne[0];
                    forgotten[3][0] = sideThree[j+2];
                }
                }
                finalStepsList.add(new Node("Node"+i+foundNodesNumber,
                                                givenNode.nodeName,
                                                forgotten,
                                                givenNode.nodeCost+1));
            break;


            // back side >>> right turn
            case 6:
                for(int j = 0; j<3;j++){
                    if(j+4 != 6){
                    forgotten[1][j+2] = sideThree[j+4];
                    forgotten[2][j+4] = sideFour[j+2];
                }else{
                    forgotten[1][j+2] = sideThree[0];
                    forgotten[2][0] = sideFour[j+2];
                }
                forgotten[3][j+2] = sideTwo[j+2];
                }
                finalStepsList.add(new Node("Node"+i+foundNodesNumber,
                                                givenNode.nodeName,
                                                forgotten,
                                                givenNode.nodeCost+1));
            break;


            // back side <<< left turn
            case 7:
                for(int j = 0; j<3;j++){
                    if(j+4 !=6){
                    forgotten[3][j+2] = sideThree[j+4];//proper
                    forgotten[2][j+4] = sideTwo[j+2];//new
                    
                }else{
                    forgotten[3][j+2] = sideThree[0];//proper
                    forgotten[2][0] = sideTwo[j+2];//new
                }
                forgotten[1][j+2] = sideFour[j+2];//new
                }
                finalStepsList.add(new Node("Node"+i+foundNodesNumber,
                                                givenNode.nodeName,
                                                forgotten,
                                                givenNode.nodeCost+1));
            break;
        }


    //generated by ChatGPT
    forgotten = new int[4][];
        for (int k = 0; k < 4; k++) {
            forgotten[k] = finalStepsList.get(i).getNodeState(k).clone();
    }
    //generated by ChatGPT


    sideOne = ((LinkedList<Node>) finalStepsList).getLast().nodeState[0].clone();
    sideTwo = ((LinkedList<Node>) finalStepsList).getLast().nodeState[1].clone();
    sideThree = ((LinkedList<Node>) finalStepsList).getLast().nodeState[2].clone();
    sideFour = ((LinkedList<Node>) finalStepsList).getLast().nodeState[3].clone();
    }


    foundNodesList.addAll(finalStepsList);
    return (LinkedList<Node>) finalStepsList;
    }



//this method takes array of nodes and a goal state and sorts the array according to 
//how close a node is from the array to the goal state (refference_node)
public LinkedList<Node> sortingNodesPriority(Node refferenceNode, LinkedList<Node> givenNodesList) {
    Node tempNode = new Node();


    for(int j = givenNodesList.size(); j>0;j--){
        for(int i = 1; i< j;i++){


            //If the node i-1 is less sorted than i, change their positions.
            if(sorter(givenNodesList.get(i-1).nodeState, refferenceNode.nodeState)<
            sorter(givenNodesList.get(i).nodeState, refferenceNode.nodeState)){
                tempNode =  givenNodesList.get(i-1);
                givenNodesList.set(i-1,givenNodesList.get(i));
                givenNodesList.set(i, tempNode);
            }


            //if the nodes have the same number of matching sides, check their cost.
            if(sorter(givenNodesList.get(i-1).nodeState, refferenceNode.nodeState) ==
            sorter(givenNodesList.get(i).nodeState, refferenceNode.nodeState)){
                
                if(givenNodesList.get(i).nodeCost <
                givenNodesList.get(i-1).nodeCost){
                    tempNode =  givenNodesList.get(i-1);
                    givenNodesList.set(i-1,givenNodesList.get(i));
                    givenNodesList.set(i, tempNode);
                }
            }
        }
    }

    return givenNodesList;
}


// takes 2 nodes and compares them returning a number of matching centers.
private int sorter(int[][] givenNode, int[][] referenceNode){
    int basesNumber = 0;
    for(int i = 0;i<4;i++){
        for(int j = 0; j<3;j++){
            if(givenNode[i][j*2+1] == referenceNode[i][j*2+1]){
                basesNumber++;
            }
        }
    }
return basesNumber;
}


//checks if all the centers are the same as a refference node
public boolean matchingBases(int[][] givenNode, int[][] referenceNode) {
    for(int i = 0; i<givenNode.length;i++){
        for(int j = 0; j < 3; j++){
            if(givenNode[i][j*2+1] != referenceNode[i][j*2+1]){
                return false;
            }
        }
    }
    return true;
}


/*checks how many edges are correctly placed for the bottom side, for example:
 * Side (0)     Side(1)
 * 000000       311111
 * Side (0) despite looking correct has its 3rd (0) is in the wrong spot. The correct placement would be:
 * 000000       111111
*/
public int displacedCornersAmount(int[][] givenNode, int[][] referenceNode){
    int cornersNumber = 3;
    for(int i = 0; i<3;i++){
        if(givenNode[3][i*2] == referenceNode[3][i*2]){
            if(givenNode[i][4]==referenceNode[i][4]){
                cornersNumber--;
            }
        }
    }
    return cornersNumber;
}


//this uses 2 nodes to check the 3rd side and compare how many sides are displaced with the given number
public boolean correctlyPlacedSides(int[][] givenNode, int[][] referenceNode,
                                        int currentNumberOfDisplacedSides){
    //here I take given node and check if its sides are where they need to be...
    //e.g. there are multiple blue sides, yet only one can be bordering the red.
    int counter = 3;
    for(int i = 0; i < 3; i++){
        if(givenNode[3][i*2] == referenceNode[3][i*2]){
            if(referenceNode[i][4] == givenNode[i][4]){
                counter--;
            }
        }
    }


    if(counter == currentNumberOfDisplacedSides){
        return true;
    }

    return false;
}


//this method tries to solve for bottom side ensuring that not only it has correct edges but also that the edges are in the correct place.
public LinkedList<Node> solvingBottomSide(Node givenNode, Node goalState) {
    int displacedCornersNumber = displacedCornersAmount(givenNode.nodeState, goalState.nodeState);


    LinkedList<Node> tempNodesList = new LinkedList<Node>();
    if(displacedCornersNumber != 0){
        
        //create 64 possible states
        tempNodesList.addAll(GenerateNewState(givenNode, 0, goalState.nodeState));
        
        //dead code means that, because I used break on all of my cases in one way or anotherm the i-- never gets called
        for(int i = tempNodesList.size()-1;i>=0;i--){

            // if the current node has all of its edges in place, remove it (as it made the 2 redundant turns)
                if(tempNodesList.get(i).nodeState[3][1] == goalState.nodeState[3][1]&&
                tempNodesList.get(i).nodeState[3][3] == goalState.nodeState[3][3]&&
                tempNodesList.get(i).nodeState[3][5] == goalState.nodeState[3][5]){
                    tempNodesList.remove(i);
                    break;
                }

            
            //so, if the 3rd sides edge == to goal of the same edge and the back of that edge is also like goal
            //basically you should be on another side knowing that your side is displaced.
            for(int j = 0; j<3;j++){
                if(tempNodesList.get(i).nodeState[3][j*2] == goalState.nodeState[3][j*2]&&
                tempNodesList.get(i).nodeState[j][4] == goalState.nodeState[j][4]){
                    tempNodesList.remove(i);
                    break;
                }
            }


            //check if the pyraminx or tetraminx has displaced side with 
            //EITHER side 3 and 5 has with the same node as goal
            for(int j = 0; j<3;j++){
                if( i == tempNodesList.size()){
                    
                    if(i ==0 && tempNodesList.size()==0){
                        //You should NOT be in this if statement.
                        System.out.println("something is wrong here...");
                    }
                    i--;
                }


                //if base is equal to goal state, check its sides.
                if(tempNodesList.get(i).nodeState[j][3] == goalState.nodeState[3][j*2+1]){
                    
                    //checking right centers(3) edges(2 and 4)
                    if(j*2+2 != 6){
                        if(tempNodesList.get(i).nodeState[j][2] == goalState.nodeState[3][j*2]||
                        tempNodesList.get(i).nodeState[j][4] == goalState.nodeState[3][j*2+2]){
                            break;
                        }
                    }
                    else{
                            if(tempNodesList.get(i).nodeState[j][2] == goalState.nodeState[3][j*2]||
                            tempNodesList.get(i).nodeState[j][4] == goalState.nodeState[3][0]){
                                break;
                            }
                    }
                }


                //5,1,3
                if(tempNodesList.get(i).nodeState[j][5]== goalState.nodeState[3][Math.abs(5- (j%3 * 4))]){
                    
                    //checking left centers(3) edges(4 and 0)
                    if(j*2+4 < 6){
                        if(tempNodesList.get(i).nodeState[j][4] == goalState.nodeState[3][j*2+2]||
                        tempNodesList.get(i).nodeState[j][0] == goalState.nodeState[3][j*2+4]){
                            break;
                        }
                    }else{
                        if(tempNodesList.get(i).nodeState[j][4] == goalState.nodeState[3][Math.abs(4-(4*j-1))]||
                        tempNodesList.get(i).nodeState[j][0] == goalState.nodeState[3][-2+2*j]){
                            break;
                        }
                    }
                }
            }

            // if the node did not meet the criteria for the loop above, it is removed.
            tempNodesList.remove(i);
            break;
        }


        //for the remaining nodes, try and put them back in place
        for(int j = tempNodesList.size()-1;j>=0;j--){
            tempNodesList.addAll(GenerateNewState(tempNodesList.remove(j),  2, goalState.nodeState));
        }


        //for all the nodes that remain, check which ones are have more than or equal to number of displaced edges.
        for(int j = tempNodesList.size()-1;j>=0;j--){
            if(displacedCornersAmount(tempNodesList.get(j).nodeState, goalState.nodeState) >= displacedCornersNumber){
                tempNodesList.remove(j);
            }
        }


        //in here we are pruning nodes that are not better than their parent.
        for(int i = tempNodesList.size()-1; i>=0;i--){
            if(correctlyPlacedSides(tempNodesList.get(i).nodeState, goalState.nodeState, displacedCornersNumber-1)==false){
                tempNodesList.remove(i);
            }
        }
    }
    return tempNodesList;
}

    //this method has similar functionality as expanding_node
public LinkedList<Node> GenerateNewState(Node givenNode ,int iterationNumber, int[][] goalStatesBases) {

    //refference instead of constantly calling list_of_all_found_nodes.size()
    int foundNodesNumber = foundNodesList.size();

    LinkedList<Node> newNodesArray = new LinkedList<>();
        int[] sideOne = givenNode.getNodeState(0);
        int[] sideTwo = givenNode.getNodeState(1);
        int[] sideThree = givenNode.getNodeState(2);
        int[] sideFour = givenNode.getNodeState(3);


    for(int i = 0; i < 8; i++){

        //generated by ChatGPT
        int[][] forgotten = new int[4][];
        for (int k = 0; k < 4; k++) {
            forgotten[k] = givenNode.getNodeState(k).clone();
        }
        //generated by ChatGPT
            
        switch (i) {
            //First 6 cases (0-5) will be described from first face (0)
            //Top gains side 2 (<<< rotation)
            case 0:
                for(int j = 0; j<3;j++){
                    forgotten[0][j] = sideTwo[j];
                    forgotten[1][j] = sideThree[j];
                    forgotten[2][j] = sideOne[j];
                }
                newNodesArray.add(new Node("node"+i+foundNodesNumber,
                                            givenNode.nodeName,
                                            forgotten,
                                            givenNode.nodeCost+1));
            break;


            //Top gains side 3 (>>> rotation)
            case 1:
                for(int j = 0; j<3;j++){
                    forgotten[0][j] = sideThree[j];
                    forgotten[1][j] = sideOne[j];
                    forgotten[2][j] = sideTwo[j];
                }
                newNodesArray.add(new Node("node"+i+foundNodesNumber,
                                                givenNode.nodeName,
                                                forgotten,
                                                givenNode.nodeCost+1));
            break;


            //Right side gains side 2 (<<< rotation)
            case 2:
                for(int j = 0; j<3;j++){
                    if(j+4 != 6){
                    forgotten[0][j+2] = sideTwo[j+4]; //array length is 0-5, will throw err.
                    forgotten[1][j+4] = sideFour[j];
                }else{
                    forgotten[0][j+2] = sideTwo[0];
                    forgotten[1][0] = sideFour[j];
                    
                }
                forgotten[3][j] = sideOne[j+2];
                }
                newNodesArray.add(new Node("node"+i+foundNodesNumber,
                                                givenNode.nodeName,
                                                forgotten,
                                                givenNode.nodeCost+1));
            break;


            //Right side gains side 4(>>> rotation)
            case 3:
                for(int j = 0; j<3;j++){
                    forgotten[0][j+2] = sideFour[j];
                    if(j+4 != 6){
                    forgotten[1][j+4] = sideOne[j+2];//same here
                    forgotten[3][j] = sideTwo[j+4];
                }else{
                    forgotten[1][0] = sideOne[j+2];
                    forgotten[3][j] = sideTwo[0];
                }
                }
                newNodesArray.add(new Node("node"+i+foundNodesNumber,
                                                givenNode.nodeName,
                                                forgotten,
                                                givenNode.nodeCost+1));
            break;


            //Left side gains side 3 (>>> rotation)
            case 4:
                for(int j = 0; j<3;j++){
                    if(j+4 != 6){
                    forgotten[0][j+4] = sideThree[j+2];
                    forgotten[2][j+2] = sideFour[j+4];
                    forgotten[3][j+4] = sideOne[j+4];
                }else{
                    forgotten[0][0] = sideThree[j+2];
                    forgotten[2][j+2] = sideFour[0];
                    forgotten[3][0] = sideOne[0];
                }
                }
                newNodesArray.add(new Node("node"+i+foundNodesNumber,
                                                givenNode.nodeName,
                                                forgotten,
                                                givenNode.nodeCost+1));
            break;


            //left side gains side 4 (<<< rotation)
            case 5:
                for(int j = 0; j<3;j++){
                    if(j+4 != 6){
                    forgotten[0][j+4] = sideFour[j+4];
                    forgotten[2][j+2] = sideOne[j+4];
                    forgotten[3][j+4] = sideThree[j+2];
                }else{
                    forgotten[0][0] = sideFour[0];
                    forgotten[2][j+2] = sideOne[0];
                    forgotten[3][0] = sideThree[j+2];
                }
                }
                newNodesArray.add(new Node("node"+i+foundNodesNumber,
                                                givenNode.nodeName,
                                                forgotten,
                                                givenNode.nodeCost+1));
            break;


            // back side >>> right turn when looking from side one
            case 6:
                for(int j = 0; j<3;j++){
                    if(j+4 != 6){
                    forgotten[1][j+2] = sideThree[j+4];
                    forgotten[2][j+4] = sideFour[j+2];
                }else{
                    forgotten[1][j+2] = sideThree[0];
                    forgotten[2][0] = sideFour[j+2];
                }
                forgotten[3][j+2] = sideTwo[j+2];
                }
                newNodesArray.add(new Node("node"+i+foundNodesNumber,
                                                givenNode.nodeName,
                                                forgotten,
                                                givenNode.nodeCost+1));
            break;


            // back side <<< left turn when looking from side one
            case 7:
                for(int j = 0; j<3;j++){
                    if(j+4 !=6){
                    forgotten[3][j+2] = sideThree[j+4];//proper
                    forgotten[2][j+4] = sideTwo[j+2];//new
                    
                }else{
                    forgotten[3][j+2] = sideThree[0];//proper
                    forgotten[2][0] = sideTwo[j+2];//new
                }
                forgotten[1][j+2] = sideFour[j+2];//new
                }
                newNodesArray.add(new Node("node"+i+foundNodesNumber,
                                                givenNode.nodeName,
                                                forgotten,
                                                givenNode.nodeCost+1));
            break;
        }
    }


    foundNodesList.addAll(newNodesArray);

    //depeiding on the "iteration_number", you will either:

    switch (iterationNumber) {

        //explore it again, making 64 nodes from 1
        case 0:
            for(int k = newNodesArray.size()-1; k>=0;k--){
                newNodesArray.addAll(GenerateNewState(newNodesArray.remove(k), iterationNumber+1, goalStatesBases));
            }
        break;


        //returning
        case 1:
        break;


        //pruning nodes that have less than 9 centers in place
        case 2:
            for(int i = newNodesArray.size()-1;i>0;i--){
                if(sorter(newNodesArray.get(i).nodeState, goalStatesBases)<9){
                    newNodesArray.remove(i);
                }
            }


            for(int k = newNodesArray.size()-1; k>=0;k--){
                newNodesArray.addAll(GenerateNewState(newNodesArray.remove(k), iterationNumber+1, goalStatesBases));
            }
        break;


        //or pruning nodes that have less than 12 centers in place
        case 3:
            for(int i = newNodesArray.size()-1;i>=0;i--){
                if(sorter(newNodesArray.get(i).nodeState, goalStatesBases)<12){
                    newNodesArray.remove(i);
                }
            }
        break;
    }


    return newNodesArray;
}


// this method uses node from which it is working backwards trying to make a path
//from initial state, to the "final_node"
public void ConstructPath(Node finalNode) {

    ArrayList<Node> nodesPathArray = new ArrayList<>();
    nodesPathArray.add(finalNode);

    String referenceNode = "";
    referenceNode = finalNode.nodeParent;

    for(int i = foundNodesList.size()-1;i>-1;i--){
        if(referenceNode==foundNodesList.get(i).nodeName){
            nodesPathArray.add(foundNodesList.get(i));
            referenceNode = foundNodesList.get(i).nodeParent;
        }
    }
    HowToTurn(nodesPathArray);
}

//this method uses the constructed path, to display the node
private void HowToTurn(ArrayList<Node> nodesPathArray){
    
    System.out.println(nodesPathArray.get(nodesPathArray.size()-1));
    for(int i = nodesPathArray.size()-1; i>0;i--){
        //i-1 is the eleemt we are moving towards.
        MovesInstructions(nodesPathArray.get(i-1).nodeState, nodesPathArray.get(i).nodeState);
        System.out.println(nodesPathArray.get(i-1));
    }
}


//this method is telling which turn you need to make to reach the next state.
private void MovesInstructions(int[][] nodeData, int[][] node) {
        //node is: current state
        //data_of_node is next state
        if(node[0][1]==nodeData[1][1]){
            System.out.println("Next move is turning top side right >>>");
        }
        if(node[0][1]==nodeData[2][1]){
            System.out.println("Next move is turning top side left <<<");
        }


        if(node[0][3]==nodeData[1][5]){
            System.out.println("Next move is turning right side away from you >>>");
        }
        if(node[0][3]==nodeData[3][1]){
            System.out.println("Next move is turning right side towards you <<<");
        }


        if(node[0][5]==nodeData[2][3]){
            System.out.println("Next move is turning left side away from you <<<");
        }
        if(node[0][5]==nodeData[3][5]){
            System.out.println("Next move is turning left side towards you >>>");
        }


        if(node[1][3]==nodeData[2][5]){
            System.out.println("Next move is turning back side left <<<");
        }
        if(node[1][3]==nodeData[3][3]){
            System.out.println("Next move is turning back side right >>>");
        }
}


//this adds initial state to lost of all nodes.
public void AddInitialState(Node start) {
    this.foundNodesList.add(start);
}
}
//Author OlegKov33