//This class generates a new node using an input as its starting point.
public class RandomNodeGenerator {
    int[][]nodeState = new int[4][6];


    RandomNodeGenerator(int[][] data2, int numberOfTurns){
        nodeState = GenerateNewState(numberOfTurns, data2);
    }


    RandomNodeGenerator(){
        int[][] defaultNodeState = {{0,0,0,0,0,0},{1,1,1,1,1,1},{2,2,2,2,2,2},{3,3,3,3,3,3}};
        nodeState = GenerateNewState(3, defaultNodeState);
    }


    public int[][] getNodeData() {
        return nodeState;
    }


//This method uses the input provided as a 2d array and creats a new array out of that.
//number of turns, is how complicated you wish to make your pyraminx or tetraminx.
    private int[][] GenerateNewState(int numberOfTurns, int[][] givenNodeState) {
        int[][] newNodeState = new int[givenNodeState.length][givenNodeState[0].length];

        for (int i = 0; i < givenNodeState.length; i++) {
            newNodeState[i] = givenNodeState[i].clone();
        }


        for (int i = 0; i < numberOfTurns; i++) {
            int[] sideOne = newNodeState[0];
            int[] sideTwo = newNodeState[1];
            int[] sideThree = newNodeState[2];
            int[] sideFour = newNodeState[3];

            int randomNumber = (int) (Math.random() * 8);
            int[][] tempNodeState = new int[4][];

            //generated by ChatGPT
            for (int k = 0; k < 4; k++) {
                tempNodeState[k] = newNodeState[k].clone();
            }
            //generated by ChatGPT

            //This will let you know which turns the method is doing
            //System.out.println(randomNumber);
            switch (randomNumber) {
                
                //Top gains side 2 (<<< rotation)
                case 0:
                    for (int j = 0; j < 3; j++) {
                        tempNodeState[0][j] = sideTwo[j];
                        tempNodeState[1][j] = sideThree[j];
                        tempNodeState[2][j] = sideOne[j];
                    }
                    break;


                //Top gains side 3 (>>> rotation)
                case 1:
                    for (int j = 0; j < 3; j++) {
                        tempNodeState[0][j] = sideThree[j];
                        tempNodeState[1][j] = sideOne[j];
                        tempNodeState[2][j] = sideTwo[j];
                    }
                    break;


                //Right side gains side 2 (<<< rotation)
                case 2:
                    for (int j = 0; j < 3; j++) {
                        if (j + 4 != 6) {
                            tempNodeState[0][j + 2] = sideTwo[j + 4];
                            tempNodeState[1][j + 4] = sideFour[j];
                        } else {
                            tempNodeState[0][j + 2] = sideTwo[0];
                            tempNodeState[1][0] = sideFour[j];
                        }
                        tempNodeState[3][j] = sideOne[j + 2];
                    }
                    break;


                //Right side gains side 4(>>> rotation)
                case 3:
                    for (int j = 0; j < 3; j++) {
                        tempNodeState[0][j + 2] = sideFour[j];
                        if (j + 4 != 6) {
                            tempNodeState[1][j + 4] = sideOne[j + 2];
                            tempNodeState[3][j] = sideTwo[j + 4];
                        } else {
                            tempNodeState[1][0] = sideOne[j + 2];
                            tempNodeState[3][j] = sideTwo[0];
                        }
                    }
                    break;


                //Left side gains side 3 (>>> rotation)
                case 4:
                    for (int j = 0; j < 3; j++) {
                        if (j + 4 != 6) {
                            tempNodeState[0][j + 4] = sideThree[j + 2];
                            tempNodeState[2][j + 2] = sideFour[j + 4];
                            tempNodeState[3][j + 4] = sideOne[j + 4];
                        } else {
                            tempNodeState[0][0] = sideThree[j + 2];
                            tempNodeState[2][j + 2] = sideFour[0];
                            tempNodeState[3][0] = sideOne[0];
                        }
                    }
                    break;


                //left side gains side 4 (<<< rotation)
                case 5:
                    for (int j = 0; j < 3; j++) {
                        if (j + 4 != 6) {
                            tempNodeState[0][j + 4] = sideFour[j + 4];
                            tempNodeState[2][j + 2] = sideOne[j + 4];
                            tempNodeState[3][j + 4] = sideThree[j + 2];
                        } else {
                            tempNodeState[0][0] = sideFour[0];
                            tempNodeState[2][j + 2] = sideOne[0];
                            tempNodeState[3][0] = sideThree[j + 2];
                        }
                    }
                    break;


                // back side >>> right turn
                case 6:
                
                    for (int j = 0; j < 3; j++) {
                        if (j + 4 != 6) {
                            tempNodeState[1][j + 2] = sideThree[j + 4];
                            tempNodeState[2][j + 4] = sideFour[j + 2];
                        } else {
                            tempNodeState[1][j + 2] = sideThree[0];
                            tempNodeState[2][0] = sideFour[j + 2];
                        }
                        tempNodeState[3][j + 2] = sideTwo[j + 2];
                    }
                    
                    break;


                // back side <<< left turn
                case 7:
                    for (int j = 0; j < 3; j++) {
                        if (j + 4 != 6) {
                            tempNodeState[3][j + 2] = sideThree[j + 4];
                            tempNodeState[2][j + 4] = sideTwo[j + 2];
                        } else {
                            tempNodeState[3][j + 2] = sideThree[0];
                            tempNodeState[2][0] = sideTwo[j + 2];
                        }
                        tempNodeState[1][j + 2] = sideFour[j + 2];
                    }
                    break;
            }

            //this line take the newly made array(forgotten) and puts it into the
            //array that will be the starting point (newData)
            newNodeState = tempNodeState;
        }


        //This creates a handy output where you can see the array of integers that will be explored
        // example of output: {{0,0,3,1,1,2},{2,1,1,2,3,3},{2,2,2,3,3,3},{0,0,1,1,0,0}};
        String output = "{";
        for (int i = 0; i < newNodeState.length; i++) {
            output+="{";
            for (int j = 0; j < newNodeState[0].length; j++) {
                output += newNodeState[i][j] + ",";
            }
            output = output.substring(0, output.length()-1);
            output+="},";
        }
        output = output.substring(0, output.length()-1);
        output+="};";
        System.out.println(output);


        return newNodeState;
    }
}
//Author OlegKov33